### ISSUE TITLE
Application in taskbar on Windows

### ISSUE THREAD

**Issue by ilyamore88** [codex-team/devops-toolbox-app#17]
If I open the application on windows, I get an icon of the application in the taskbar.
![image](https://user-images.githubusercontent.com/37909603/102406624-e9653f80-3ffb-11eb-957d-bea1f361927a.png)

**Comment by talyguryn** [comment]
is it bundled application or development run from sources?

**Comment by ilyamore88** [comment]
It's a development run. With bundled application, I have a normal icon, but I think I shouldn't see the application in my taskbar.
![image](https://user-images.githubusercontent.com/37909603/103083584-cafbd700-45ed-11eb-96d7-f90d7647af84.png)

**Comment by talyguryn** [comment]
v0.0.13

if application is not focused:
![image](https://user-images.githubusercontent.com/15259299/103131925-e204fc80-46b3-11eb-9da0-d65045f55d3e.png)

on focus:
![image](https://user-images.githubusercontent.com/15259299/103131963-0d87e700-46b4-11eb-9e56-7f837f8857e2.png)
